### ISSUE TITLE
Order of \em and \bf matters

### ISSUE THREAD

**Issue by retorquere** [retorquere/bibtex-parser#10]
@njbart, with these two snippets:

```
{aa\bf bb\em cc}

{aa\em bb\bf cc}
```

I had expected to final `cc` in both cases to be slanted and bold, but in the 2nd case, they're just bold. Do you know what rule could be underlying here?

**Comment by njbart** [comment]
I can reproduce this, but I have no idea why exactly. It seems you shouldn’t use `\bf` or `\em` anyway: see, e.g., http://www.texfaq.org/FAQ-2letterfontcmd and https://tex.stackexchange.com/questions/41681/correct-way-to-bold-italicize-text.

**Comment by njbart** [comment]
Ok, what I think is the correct answer is here: https://tex.stackexchange.com/questions/25911/what-is-the-difference-between-em-and-emph

**Comment by retorquere** [comment]
I have a sufficient approximation for this behavior now, and as you said, people shouldn't be using it. But it's in my test suite which means I've found it at least once in the wild.
