### ISSUE TITLE
Cannot handle "textquotedblleft" and "textquotedblright"

### ISSUE THREAD

**Issue by crystalfp** [retorquere/bibtex-parser#13]
I'm parsing a bibliography that has abstracts containing `{\textquotedblleft}` and `{\textquotedblright}` but the parser gives an exception. Tried adding `verbatimCommands: ["textquotedblleft", "textquotedblright"],` to `parse()` but no change. Reproduce parsing the following entry:
```
@Article{Stahl2015,
  author       = {Stahl, Aimee E. and Feigenson, Lisa},
  date         = {2015},
  journaltitle = {Science},
  title        = {Observing the unexpected enhances infants’ learning and exploration},
  doi          = {10.1126/science.aaa3799},
  issn         = {0036-8075},
  number       = {6230},
  pages        = {91--94},
  url          = {https://science.sciencemag.org/content/348/6230/91},
  volume       = {348},
  abstract     = {Infants use {\textquotedblleft}unexpectedness{\textquotedblright} as a cue for learning. Stahl and Feigenson studied how babies reacted when objects behaved in surprising ways (see the Perspective by Schulz). Babies who saw apparently solid and weighty objects moving through a wall or past the edge of a table without falling looked intently at them. When given the opportunity to explore these peculiar objects, they did so by banging them on the floor{\textemdash}as if to test their solidity{\textemdash}or dropping them{\textemdash}as if to test their weightiness.},
}
```
Suspect  I will have the same error with `{\textemdash}`.
The code (typescript) is simply:
```
import fs from "fs";
import {Bibliography, parse as parseBibtex} from "@retorquere/bibtex-parser";
const input = fs.readFileSync("bug.bib", "utf8");
const bibliographyEntries = parseBibtex(input, {
    verbatimFields: [
	"url", "note", "doi", "file", "keywords", "files", "eprint", "verba", "verbb", "verbc"],
    sentenceCase: false,
    verbatimCommands: ["textquotedblleft", "textquotedblright"],
}) as Bibliography;
console.log(JSON.stringify(bibliographyEntries, undefined, 2));
```
Thanks for looking!
mario

**Comment by crystalfp** [comment]
No problem for `{\textemdash}` It is parsed as — without problems. Idem for `{\url abc}` parsed as `abc`.
Instead `abstract = {Infants use {\textquotedblleft}unexpectedness{\textquotedblright} as a cue}` gives problem having or not having defined `verbatimCommands`

**Comment by crystalfp** [comment]
Seems the two entries are simply missing from `unicode2latex\tables\latex.json`. Anyway it is strange that `verbatimCommand` does not intercept them (or maybe I have misunderstood this option).

**Comment by retorquere** [comment]
Poor documentation on my part. That option changes the behavior for commands that are known to have arguments, but since these don't, it doesn't do anything. I've updated unicode2latex, so updating that will likely fix it for you, but the [test suite is running](https://travis-ci.org/github/retorquere/bibtex-parser/builds/745036136) for the package in this repo for a version that includes this updated unicode2latex.

You can suppress errors by using a no-op error handler such as `function(err) { console.log(err) }` in which case the unhandled command is just ignored, but the default behavior is to throw an error.

**Comment by crystalfp** [comment]
Solved thanks!
Imagine you have added this case in your extensive test suite.
Thanks again for your work!
mario

**Comment by retorquere** [comment]
Yep, added to the test suite.
