### ISSUE TITLE
Dead link in documentation

### ISSUE THREAD

**Issue by crystalfp** [retorquere/bibtex-parser#17]
Every reference to `http://retorque.re/bibtex-parser/` in the documentation and under NPM page returns 404 page not found.
Where the documentation lives now?
Thanks!
mario

**Comment by retorquere** [comment]
Thanks for the heads-up -- it's still at the same place, but docs generation was broken.

**Comment by crystalfp** [comment]
Thanks, solved!

**Comment by crystalfp** [comment]
Unfortunately the issue returned. Today here: http://retorque.re/bibtex-parser/  Bibliography or Entry or ParserOptions returns 404 page not found.

**Comment by retorquere** [comment]
I've republished and they're back up. No idea what causes this, I haven't actually changed the site contents.
