### ISSUE TITLE
LaTeX `quotation` environment in `note` field yields `undefined` in converted text

### ISSUE THREAD

**Issue by hans** [retorquere/bibtex-parser#18]
Hi, excellent work on this parser, thank you for developing it!
I noticed a bug in parsing LaTeX notes.

## Minimal reproduction

```javascript
const bib = `
@article{demonstration,
note = {\\begin{quotation}
sdadsafsf
\\end{quotation}

\\par
PRIME und SAT sind exponenziall ybd gelten in der Praxis als nicht l\\"osbar. (\\href{zotero://open-pdf/library/items/VAB33DNE?page=30}{note on p.30})
\\par}
}
`;

const parser = require("@retorquere/bibtex-parser");
parser.parse(bib).entries[0].fields.note
```

For me the above script yields
```javascript
[
  'undefined sdadsafsf undefined \n' +
    '\n' +
    'PRIME und SAT sind exponenziall ybd gelten in der Praxis als nicht lösbar. (zotero://open-pdf/library/items/VAB33DNE?page=30)'
]
```

I believe this has something to do with the use of the `quotation` environment -- when I remove the `\begin` and `\end` tags here, everything works fine. AFAIK this is valid BibLaTeX usage, but I may be wrong!

## Desired behavior

Yield a plain-text conversion with no trace of the `quotation` environment, `undefined` or otherwise. Alternatively, use a plaintext standard like `>` to denote quotations.

(unescaped bibtex here:)
```
@article{demonstration,
note = {\begin{quotation}
sdadsafsf
\end{quotation}

\par
PRIME und SAT sind exponenziall ybd gelten in der Praxis als nicht l\"osbar. (\href{zotero://open-pdf/library/items/VAB33DNE?page=30}{note on p.30})
\par}
}
```

**Comment by retorquere** [comment]
Thanks for reporting this -- 5.3.0 fixes this but will also trigger test failures in my test suite if new unhandled environments would come in. In no-fail mode (`errorHandler` == `false`) it will now just return the content for unhandled environments.
