### ISSUE TITLE
Support for links

### ISSUE THREAD

**Issue by abdullahibnnadjo** [retorquere/bibtex-parser#19]
Hi,

Currently, the parser translates link commands to raw url, i.e.: 
```tex
\href{http://zotero://open-pdf/library/items/EK2Y9JUB?page=21}{note on p.21}}
```
to only `http://zotero://open-pdf/library/items/EK2Y9JUB?page=21`
I expect the output to be:
```html
<a href="http://zotero://open-pdf/library/items/EK2Y9JUB?page=21">note on p.21</a>
```

Is it possible to make this enhancement, or does this change have some other implications that would make it impossible to do ?

I dug a bit to maybe make a PR for this, but I’m unsure about the `Block` translation (maybe the part [`convert_block`](https://github.com/retorquere/bibtex-parser/blob/9cce8d68ad88659e4fa4f0b12afbe4c686fa8e85/index.ts#L1796) ?)

You can find the reference issue and details here : hans/obsidian-citation-plugin#125 

Thanks !

**Comment by retorquere** [comment]
Version 6.0.0 will be published on npm when the test suite is finished, which will convert links to `<a>` tags.

**Comment by evolve2k** [comment]
Looks like version 6.0.0 dropped in Nov 2021, @abdullahibnnadjo [abdullahibnnadjo](https://github.com/abdullahibnnadjo) is this issue now fixed? 

Can this be closed?
