### ISSUE TITLE
Cannot find module tslib

### ISSUE THREAD

**Issue by fernandobt8** [retorquere/bibtex-parser#21]
running bibtex-parser throw the error
```
node:internal/modules/cjs/loader:988
  throw err;
  ^

Error: Cannot find module 'tslib'
```
installing 'tslib' to your project solves it, don't know if this was the expected behaviour

**Comment by retorquere** [comment]
It's not, I'll look into it.

**Comment by retorquere** [comment]
New version is out that doesn't have the dependency.

**Comment by fernandobt8** [comment]
worked like a charm :smile:
