### ISSUE TITLE
unable to disable sentence case for titles

### ISSUE THREAD

**Issue by scheibo** [retorquere/bibtex-parser#23]
previously i was able to use `bibtex.parse(file, {sentenceCase: false});` to get bibtext to not mangle my titles, i have no idea what i'm supposed to use with version 9 of bibtex, it appears from https://github.com/retorquere/bibtex-parser/blob/76878ea0e663997babec388f3f7b39f0f1b66e97/index.ts#L949 that `toSentenceCase` gets run no matter what.

**Comment by retorquere** [comment]
Do you have an MWE for me?

**Comment by retorquere** [comment]
Oh the options format has changed: http://retorque.re/bibtex-parser/interfaces/index.Options.html
