### ISSUE TITLE
Errors from @Preamble

### ISSUE THREAD

**Issue by crystalfp** [retorquere/bibtex-parser#9]
JabRef let you add a `@Preamble{}` section to the library, apparently without constraints on the content. But if I start my library with (JabRef provided):
```
% Encoding: UTF-8

@Preamble{Oppla!}
```
the parser complains:
```
  "errors": [
    {
      "message": "Expected \",\" but end of input found.",
      "line": 4,
      "column": 1,
      "source": "% Encoding: UTF-8\r\n\r\n@Preamble{Oppla!}\r\n"
    }
  ],
```
But shouldn't anything outside the entries, comments and strings be ignored?
Or, and this could be a feature request, not recognized entry like `@Preamble` be converted in a Bibliography entry like `@comment` are?

Thanks for your attention!
mario

**Comment by retorquere** [comment]
Can you try 3.2.0?

**Comment by crystalfp** [comment]
Tried 3.2.0 and it works!
The only thing that sound strange to me is that the result is a string and not an array like comments. Not a problem for me, just want to understand if this is correct.
And the not-realistic case of two `@Preamble` results in a concatenation of the two contents, not, as for `comments`, an array of two entries.
Just curious.
Thanks again!
mario

**Comment by retorquere** [comment]
I can make it an array, no issue.

**Comment by crystalfp** [comment]
The `comments` field is OK as it is now.
For the `preamble` maybe an array makes it consistent with the rest of the Bibliography.
Anyway, right now I don't plan to use this field, comments is sufficient for my needs.
Thanks!
mario

**Comment by retorquere** [comment]
I'm not going to change the comments. I rely on the comments being an array. I can change the preamble to be an arrey, it'll go up as 3.2.1

**Comment by crystalfp** [comment]
After reading http://maverick.inria.fr/~Xavier.Decoret/resources/xdkbibtex/bibtex_summary.html#preamble I have to retract part of my [comment](https://github.com/retorquere/bibtex-parser/issues/9#issuecomment-641270283). It is OK to concatenate `@Preamble`s as it is now.

**Comment by retorquere** [comment]
It's already out as 3.2.1. But it's easier to cleanly do concatenation than splitting, so I'm leaving it this way.

**Comment by crystalfp** [comment]
Seems in 3.2.1 you switched the changes. Now multiple `@Preamble`s are different entries in the preamble array, instead multiple `@comments` are concatenated together.
Normally there is a single preamble (JabRef enforces this) and multiple comments, please undo the comments change so each of them is an entry in the comments array. This way I can process my comments and skip the `jabref-meta` ones. Instead the preamble array is ok as it is now in 3.2.1
Thanks!
mario

**Comment by retorquere** [comment]
When I parse that file, I get both strings and preamble as string arrays.

**Comment by retorquere** [comment]
in other words, I cannot reproduce the problem, nor think of a way it could happen, and it passes my many tests which test for this. I'd need to know what you do exactly to get this result.

**Comment by crystalfp** [comment]
Nevermind. It was my fault. A concatenation left before the print that should have been after. As it should, there are two comments and two entries in comments array. Sorry for the noise.
mario
